### ISSUE TITLE
save_environment won't update

### ISSUE THREAD

**Issue by infmon** [drunner/drunner#12]
save_environment works fine for saving a new environment value, but if I try to replace an existing one (if, for example, a 'configure' action gets called a second time), the new value is ignored

**Comment by j842** [comment]
Haven't reproduced yet - does the servicevars.sh file in the dService's install directory contain the updated string?

**Comment by infmon** [comment]
I could have sworn that was what was happening.  Let me check again, I may have conflated an old issue with something else

**Comment by infmon** [comment]
I may be looking in the wrong place, (~/drunner/dService/<service>/servicevars.sh), but I can't see the environment variables in there at all, regardless of value.  I'm only seeing IMAGENAME

**Comment by infmon** [comment]
https://github.com/infmon/testvalue.git

ddev build
TEST_VALUE=hello envtest configure
envtest enter
   echo $TEST_VALUE
TEST_VALUE=howdy envtest configure
envtest enter
   echo $TEST_VALUE


Second echo command should return 'howdy' but it returns 'hello'

With dRunner 0.5 r15, built May 9

**Comment by j842** [comment]
Above instructions only modify an environment variable on the host so would not be expected to change anything in the container.

Do you mean something like:
testvalue configure "hello envtest configure"
?

**Comment by infmon** [comment]
"envtest configure" reads in the environment variable "TEST_VALUE" and then calls save_environment with the value.  You could easily rewrite envtest to take a parameter, in which case it would be "envtest configure <VALUE>"

**Comment by j842** [comment]
Just wrapping my head around this (deleted my previous confusing comment). 

1) On a clean install of envtest the above example works fine for me, with howdy the second time. In your test did you previously used save_environment (i.e. envtest configure)? If so see (3) below.

2) In the above example you're not calling envtest configure, so you're not actually using save_environment...

3) If you do call envtest configure before envtest enter each time above, then only the first value will stick. It'll go like this:
a) TEST_VALUE=hello
b) envtest configure 
   - this gets dRunner to store TEST_VALUE using save_environment, now every time envtest is run TEST_VALUE is set to hello by dRunner
c) envtest enter
   - dRunner has set TEST_VALUE to hello here
d) echo $TEST_VALUE
   - shows hello
e) TEST_VALUE=howdy
f) envtest configure 
   - dRunner sets TEST_VALUE to hello again here (since it's been saved as hello), overriding the value just set on the command line.
   - configure then calls save_environment with the value hello (not howdy), so no change.
g) envtest enter
   - again TEST_VALUE is set to hello by dRunner
h) echo $TEST_VALUE 
   - if in container it'll echo hello
   - if on host it'll echo howdy

To get around this you'd need to use a different environment variable name at the command line or pass it as a parameter instead.

4) The variables file is in here, under the dRunner install path:
hostVolumes/envtest/environment/servicerunner_env.sh

**Comment by infmon** [comment]
Yes, that makes perfect sense!  So not a bug in dRunner, just in my brain :)
